### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [4]:
import numpy as np

In [5]:
a = np.array([[3,2,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]])
print("Original array: \n", a)
print("Find the missing data of the said array: \n",np.isnan(a))

Original array: 
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array: 
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [8]:
a= np.array([1,2,3,4,5])
b=np.array([1,2,4,6,5])
print(np.equal(a,b))

[ True  True False False  True]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [9]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [14]:
a=[1,2,3,4,5]
b = (5,6,7,8,9)
print("Converted list to numpy: ", np.array(a))
print("Converted tuple to numpy: ",np.array(b))

Converted list to numpy:  [1 2 3 4 5]
Converted tuple to numpy:  [5 6 7 8 9]


###### 5. Write a NumPy program to find common values between two arrays.

In [15]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,6])
c=np.intersect1d(a,b)
print(c)

[2 3 4]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [16]:
a=np.arange(1,7)
print("Original array: \n ", a)
b=np.reshape(a,(3,2))
print("Reshape 3x2: \n",b)
c=np.reshape(a,(2,3))
print("Reshape 2x3: \n", c)

Original array: 
  [1 2 3 4 5 6]
Reshape 3x2: 
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3: 
 [[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [18]:
a=np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:\n", a)
b,c=np.unique(a,return_counts=True)
print("Frequency of unique values of the said array: \n",b,"\n",c)

Original array:
 [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array: 
 [10 20 30 40 50] 
 [3 4 2 2 1]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [19]:
a=np.array([[0,0,0],[1,2,3],[4,5,6]])
print("Original arrays:")
print("Array-1:\n",a)
b=np.array([10,11,12])
print("Array-2:\n",b)
print("New Array:\n",a+b)

Original arrays:
Array-1:
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2:
 [10 11 12]
New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [20]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [21]:
a=np.arange(0,16).reshape(4,4)
print("Original array:\n",a)
b=a[0:2,2:4]
print("Extracted data: Third and fourth elements of the first and second rows :\n",b)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: Third and fourth elements of the first and second rows :
 [[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [23]:
a=np.datetime64("today","D")
print("Today's Date: ",a)
b=np.datetime64("today","D") - np.timedelta64(1,'D')
print("Yesterday's Date: ",b)
c=np.datetime64("today","D") + np.timedelta64(1,'D')
print("Tomorrow's Date: ",c)

Today's Date:  2022-03-12
Yesterday's Date:  2022-03-11
Tomorrow's Date:  2022-03-13


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [25]:
print("First Monday in May 2017:\n",np.busday_offset('2017-05',0,roll='forward', weekmask='Mon'))

First Monday in May 2017:
 2017-05-01
