### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [8]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [17]:
import numpy as np
print("array of ten zeros:\n",np.zeros(10))

array of ten zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
import numpy as np
print("array of ten ones:\n",np.ones(10))

array of ten ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
import numpy as np
print("array of ten fives:\n", np.ones(10)*5)

array of ten fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [51]:
a=np.arange(30,71)
print("arrays of intergers 30 to 70:\n",a)

arrays of intergers 30 to 70:
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [53]:
a=np.arange(10,51,2)
print("arrays of all even integers 10 to 50:\n",a)

arrays of all even integers 10 to 50:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [60]:
a=np.eye(3)
print("identity matrix 3*3\n",a)

identity matrix 3*3
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [70]:
a=np.random.rand(1)
print("random numbers between 0 and 1:\n",a)

random numbers between 0 and 1:
 [0.6760351]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [75]:
a=np.random.rand(1,15)
#a=np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:\n",a)

15 random numbers from a standard normal distribution:
 [[0.5829061  0.05527323 0.79598558 0.13200071 0.15923676 0.669166
  0.93587305 0.50112883 0.65463782 0.0451872  0.7260871  0.72233471
  0.71878541 0.0397161  0.2072777 ]]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [108]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
    print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [105]:
a=np.array([1,8,3,5])
b=np.array([10,1,4,10])
c=a*b
print("Vector-1 \n", a)
print("Vector-2\n", b)
print("Multiply the values of two said vectors: \n", c)

Vector-1 
 [1 8 3 5]
Vector-2
 [10  1  4 10]
Multiply the values of two said vectors: 
 [10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [119]:
a=np.arange(12,38)
print("Original array:\n", a)
b=a[::-1]
print("Reverse array: \n",b)

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array: 
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [122]:
#np.eye(5)
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [123]:
a=np.array([[0,1],[2,3]])
print("Original array: \n", a)
print("Sum of all elements:\n",np.sum(a))
print("Sum of each column: \n",np.sum(a,axis=0))
print("Sum of each row:\n",np.sum(a,axis=1))## code here

Original array: 
 [[0 1]
 [2 3]]
Sum of all elements:
 6
Sum of each column: 
 [2 4]
Sum of each row:
 [1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [124]:
a=np.array([4,5])
b=np.array([7,10])
c=np.dot(a,b)
print("Original vectors: \n",a,"\n",b)
print("Inner product of said vectors: \n",c)

Original vectors: 
 [4 5] 
 [ 7 10]
Inner product of said vectors: 
 78
